![Numpy](img/numpy.png)

Bienvenue dans ce notebook d'initiation à **NumPy**, une bibliothèque essentielle pour la data science avec Python.

🎯 Objectif : Comprendre l'essentiel de NumPy

---

## 📌 Sommaire :
1. Création de tableaux
2. Dimensions et forme
3. Indexation & slicing
4. Opérations vectorielles
5. Fonctions statistiques
6. Manipulation et fusion
7. Broadcasting

---


# Introduction

NumPy (**Numerical Python**) est la bibliothèque de base pour le calcul scientifique avec Python. Elle permet de manipuler des structures de données puissantes appelées **arrays** ou **tableaux**, optimisées pour la performance et la simplicité d’usage. NumPy est utilisé par presque toutes les bibliothèques de l’écosystème <a href='https://pydata.org/'>PyData</a> (comme **Pandas**, **Scikit-learn**, **SciPy**) et constitue une compétence fondamentale pour tout data scientist ou ingénieur en machine learning.


<img src="img/numpy_foundation.png" alt="Numpy" style="display:block; margin-left:auto; margin-right:auto;">

**Pourquoi Numpy ?**

Contrairement aux listes Python classiques, les tableaux NumPy sont :
- Plus **rapides** et moins gourmands en mémoire
- Facilement extensibles à plusieurs dimensions (**vecteurs**, **matrices**, **tenseurs**)
- Compatibles avec des **opérations vectorisées** et du **broadcasting**
- Intégrés dans toutes les bibliothèques majeures de la **data science**

**Chargement de la librairie Numpy**

In [3]:
import numpy as np

# 1. 🎲 Création de tableaux NumPy

## 1.1. Depuis des objets Python

NumPy permet de créer facilement des tableaux numériques notamment à parti de listes Python

In [4]:
my_list = [5, 10, 15]           # liste Python contenant trois entiers
my_array = np.array(my_list)    # convertit cette liste en tableau numpy, ce qui permet ensuite d’appliquer des opérations vectorielles

display(my_list)
display(my_array)

[5, 10, 15]

array([ 5, 10, 15])

## 1.2. Tableaux 1D et 2D : vecteurs et matrices

La structure de base de NumPy est le `tableau` (array). Il peut être :

**1D** : vecteur

**2D** : matrice

ou **nD** (plusieurs dimensions)

In [5]:
# Vecteur 1D
v = np.array([1, 2, 3])

# Matrice 2D
m = np.array([[1, 2], [3, 4]])

display(type(v))
display(v)
print("---------------")
display(type(m))
display(m)

numpy.ndarray

array([1, 2, 3])

---------------


numpy.ndarray

array([[1, 2],
       [3, 4]])

🧠 **À retenir** : une matrice 2D peut contenir une seule ligne ou une seule colonne, mais reste bien en deux dimensions.

### 🧩 Exercices

> Créez et affichez un vecteur contenant les entiers de 10 à 20

In [6]:
# Votre code ici
int_10_to_20 = np.array(range(10,20))
display(int_10_to_20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

> Créez et affichez une matrice 3x3 avec les entiers de 1 à 9

In [20]:
# Votre code ici
#matrix_3x3 = np.array([range(1,4),range(4,7),range(7,10)])
# alternative mthod 
matrix_3x3 = np.arange(1, 10).reshape(3, 3)
matrix_3x3
display(matrix_3x3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 1.3. Séquences numériques

Il est facile de générer facilement des suites de nombres avec Numpy.

In [21]:
sequence_1 = np.arange(0, 10, 2)    # crée une suite de nombres allant de 0 à 8 avec un pas de 2
sequence_2 = np.linspace(0, 1, 5)   # génère 5 valeurs également espacées entre 0 et 1 inclus

display(sequence_1)
display(sequence_2)

array([0, 2, 4, 6, 8])

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### 🧩 Exercices

> Créez un tableau avec des valeurs entre 0 et 20 espacées de 5

In [23]:
# Votre code ici
array_0_to_20 = np.array(range(0,20,5))
display(array_0_to_20)

array([ 0,  5, 10, 15])

> Utilisez ``linspace`` pour créer un tableau de 50 valeurs entre -1 et 1

In [25]:
# Votre code ici
array_linspace = np.array(np.linspace(-1,1,50))
display(array_linspace)

array([-1.        , -0.95918367, -0.91836735, -0.87755102, -0.83673469,
       -0.79591837, -0.75510204, -0.71428571, -0.67346939, -0.63265306,
       -0.59183673, -0.55102041, -0.51020408, -0.46938776, -0.42857143,
       -0.3877551 , -0.34693878, -0.30612245, -0.26530612, -0.2244898 ,
       -0.18367347, -0.14285714, -0.10204082, -0.06122449, -0.02040816,
        0.02040816,  0.06122449,  0.10204082,  0.14285714,  0.18367347,
        0.2244898 ,  0.26530612,  0.30612245,  0.34693878,  0.3877551 ,
        0.42857143,  0.46938776,  0.51020408,  0.55102041,  0.59183673,
        0.63265306,  0.67346939,  0.71428571,  0.75510204,  0.79591837,
        0.83673469,  0.87755102,  0.91836735,  0.95918367,  1.        ])

## 1.4. Génération de données aléatoires

NumPy propose également un module random pour créer des tableaux remplis de valeurs aléatoires.

In [26]:
# Entiers aléatoires (entre 0 et 10, exclu)
object_1 = np.random.randint(0, 10)           # un seul entier aléatoire entre 0 et 9
object_2 = np.random.randint(0, 10, (3, 3))   # matrice 3x3 d'entiers aléatoires entre 0 et 9

# Flottants aléatoires uniformes entre 0 et 1
object_3 = np.random.rand(4)                 # vecteur de 4 flottants tirés d'une distribution uniforme [0, 1)
object_4 = np.random.rand(4, 4)              # matrice 4x4 de flottants tirés d'une distribution uniforme [0, 1)

# Flottants aléatoires selon une loi normale (moyenne = 0, écart-type = 1)
object_5 = np.random.randn(4)                # vecteur de 4 flottants selon une loi normale centrée réduite
object_6 = np.random.randn(4, 4)             # matrice 4x4 de flottants selon une loi normale centrée réduite              

display(object_1)
display(object_2)
display(object_3)
display(object_4)
display(object_5)
display(object_6)

0

array([[1, 2, 0],
       [1, 5, 7],
       [5, 3, 3]], dtype=int32)

array([0.62275618, 0.84579968, 0.26668936, 0.48878676])

array([[9.78941295e-01, 2.78117541e-01, 4.63160928e-01, 7.92205439e-01],
       [4.08853180e-01, 1.50593581e-04, 6.52438915e-01, 9.31862288e-01],
       [7.76738851e-01, 9.62448112e-01, 8.78607649e-01, 7.79643016e-01],
       [3.88647640e-01, 9.51240497e-01, 4.54089962e-01, 2.24006191e-02]])

array([ 0.64957718,  0.9980869 , -1.16988723, -0.21031911])

array([[-1.0841775 , -1.52300472, -1.73308914, -0.21703857],
       [-0.72433358, -0.775334  , -1.21180605, -0.69227263],
       [-0.31581364,  0.44303742,  1.64111756, -0.8737409 ],
       [ 0.42847777,  1.17695512,  0.75457486,  0.78225093]])

### 🧩 Exercices

> Générez un entier aléatoire entre 1 et 100

In [28]:
# Votre code ici
rand_int = np.random.randint(1,100)
rand_int

72

> Créez un tableau 1D de 10 entiers aléatoires entre 0 et 20

In [31]:
# Votre code ici
array_10_rand_int = np.random.randint(0,20,(1,10))
array_10_rand_int

array([[17,  0, 14, 17,  1,  4, 15,  3,  4, 19]], dtype=int32)

> Générez une matrice 5x5 d’entiers entre 0 et 9

In [32]:
# Votre code ici
array_5x5_rand_int = np.random.randint(0,9,(5,5))
array_5x5_rand_int

array([[0, 0, 6, 3, 3],
       [2, 5, 4, 5, 0],
       [4, 2, 3, 7, 2],
       [6, 3, 7, 0, 6],
       [6, 6, 0, 2, 8]], dtype=int32)

> Générez un vecteur de 6 flottants aléatoires entre 0 et 1

In [ ]:
# Votre code ici
array__rand_flottant_0_to_1 = np.random.rand(6)
array__rand_flottant_0_to_1

array([0.58023736, 0.70165771, 0.12326518, 0.72268032, 0.9570206 ,
       0.47164572])

> Créez une matrice 3x3 de flottants aléatoires entre 0 et 1

In [35]:
# Votre code ici
np.random.rand(3, 3)

array([[0.76146557, 0.18794161, 0.12257155],
       [0.84518033, 0.67982616, 0.10629551],
       [0.9160703 , 0.36420178, 0.52792687]])

> Générez un vecteur de 8 valeurs suivant une loi normale (moyenne 0, écart-type 1)

In [36]:
# Votre code ici
np.random.randn(8)

array([ 0.396727  ,  0.66287732,  0.80312137, -2.37013971, -0.49373256,
        0.57505759,  0.89067632,  0.88921606])

> Créez une matrice 4x4 de valeurs aléatoires selon une loi normale

In [37]:
# Votre code ici
np.random.randn(4,4)

array([[-0.61022356, -1.09936321, -1.17710218, -0.92787021],
       [ 0.5356786 , -0.02422904,  1.49277222, -0.87598295],
       [-0.78276037,  0.69330856,  0.13739441,  0.76159077],
       [ 1.12845897,  0.19661065, -0.36450159, -0.14739754]])

## 1.5. Tableaux pré-remplis

Numpy propose des fonctions pratiques pour créer rapidement des tableaux contenant des valeurs par défaut.

In [38]:
# Zéros
zeros = np.zeros(4)               # vecteur de 4 éléments contenant uniquement des zéros
zeros_matrix = np.zeros((4, 4))   # matrice 4x4 remplie de zéros

# Uns
ones = np.ones(4)                 # vecteur de 4 éléments contenant uniquement des uns
ones_matrix = np.ones((4, 4))     # matrice 4x4 remplie de uns

# Matrice identité 4x4 (matrice carrée avec des 1 sur la diagonale principale et des 0 ailleur.
# Elle joue un rôle similaire au nombre 1 pour la multiplication)
matrix_identity = np.eye(4)     


display(zeros)
display(zeros_matrix)

display(ones)
display(ones_matrix)

display(matrix_identity)

array([0., 0., 0., 0.])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

array([1., 1., 1., 1.])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### 🧩 Exercices

> Créez un vecteur de 6 zéros

In [39]:
# Votre code ici
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

> Créez une matrice 3x5 remplie de zéros

In [41]:
# Votre code ici
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

> Créez un vecteur de 10 uns

In [42]:
# Votre code ici
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

> Créez une matrice 2x3 remplie de uns

In [43]:
# Votre code ici
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

> Créez une matrice identité 8x8

In [45]:
# Votre code ici
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

# 2. 📐 Dimensions et forme des tableaux

Numpy offre des attributs très utiles pour explorer la structure des tableaux

In [ ]:
# Tableau de 0 à 11 transformé en matrice 3x4 grâce à la méthode .reshape()
# ⚠️ Attention : le produit des dimensions passées à reshape (ici 3×4 = 12) 
# doit exactement correspondre au nombre total d’éléments dans le tableau initial. Sinon, NumPy renverra une erreur !
array = np.arange(12).reshape(3, 4)        

print("Tableau :\n", array, "\n")                     # affiche le tableau
print("Forme (shape) :", array.shape, "\n")           # affiche la forme du tableau
print("Nombre de dimensions :", array.ndim, "\n")     # affiche le nombre de dimensions
print("Nombre total d'éléments :", array.size, "\n")  # affiche le nombre d'éléments
print("Type de données (dtype) :", array.dtype, "\n") # affiche le type des données

### 🧩 Exercice

> Créez une matrice de forme 6x2 à partir de np.arange().  
> Affichez sa forme, son nombre d’éléments, son nombre de dimensions.

In [50]:
# Votre code ici
array_6x2 = np.arange(12).reshape(6, 2) 
display(array_6x2)
print(f" shape: {array_6x2.shape}, num_elements: {array_6x2.size}, num_dim: {array_6x2.ndim}")

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

 shape: (6, 2), num_elements: 12, num_dim: 2


> Créez un tableau contenant les nombres de 0 à 19, puis transformez-le en matrice de 4 lignes et 5 colonnes.

In [53]:
# Votre code ici
array_0_to_19 = np.arange(20).reshape(4,5)
array_0_to_19


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

> Vous disposez d’un tableau de 18 éléments. Quelles sont les trois formes possibles que vous pouvez lui donner avec reshape() en matrice 2D ?

In [54]:
# Écrivez trois reshape différents qui fonctionnent
array_18_items = np.arange(18).reshape(1,18)
array_18_items = np.arange(18).reshape(2,9)
array_18_items = np.arange(18).reshape(3,6)



# 3. 🔍 Indexing & Slicing

Lorsque vous travaillez avec des tableaux ou matrices NumPy, il est essentiel de savoir accéder aux éléments, **extraire des lignes**, **des colonnes** ou **des sous-parties**. Cette opération s’appelle l’**indexing** (accès à un ou plusieurs éléments) et le **slicing** (extraction de tranches).

NumPy utilise une syntaxe très proche de celle des listes Python, mais adaptée aux tableaux multidimensionnels. Grâce à cela, vous pouvez :
- Accéder à une valeur précise dans un tableau 2D
- Extraire une ligne ou une colonne
- Récupérer plusieurs lignes ou colonnes avec des tranches (slices)
- Utiliser des conditions (masques logiques) pour filtrer certains éléments

Dans les exemples suivants, nous allons manipuler une matrice 3x4 pour explorer ces différentes possibilités.

In [55]:
# Matrice de travail
matrix = np.arange(12).reshape(3, 4)

print("Matrice :\n", matrix)

Matrice :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## 3.1. Indexing

**Indexing** = accès à un seul élément ou un groupe précis via des **indices explicites**.

In [ ]:
print("Première ligne :", matrix[0])                # extrait toute la première ligne
print("Dernière ligne :", matrix[-1])               # extrait toute la dernière ligne
print("Première colonne :", matrix[:, 0])           # extrait tous les éléments de la 1ère colonne, sur toutes les lignes
print("Première colonne :", matrix[:, -1])          # extrait tous les éléments de la dernière colonne, sur toutes les lignes
print("Élément ligne 0, colonne 2 :", matrix[0, 2]) # extrait'élément situé à la 1ère ligne (index 0) et à la 3e colonne (index 2)

## 3.2. Slicing

**Slicing** = accès à une plage continue d’éléments avec l’opérateur : `(start:stop:step)`.

In [ ]:
print("Lignes 0 et 1 :\n", matrix[0:2], "\n")               # extrait les deux premières lignes (lignes 0 et 1 incluses, ligne 2 exclue)
print("Colonnes 1 et 2 :\n", matrix[:, 1:3], "\n")          # extrait toutes les lignes mais seulement les colonnes 1 et 2 (3 exclue)
print("Colonnes 0, 2, ... :\n", matrix[:, ::2], "\n")       # extrait toutes les lignes mais une colonne sur deux (colonne 0, 2...)
print("Éléments > 5 :\n", matrix[matrix > 5], "\n")         # extrait tous les éléments dont la valeur est strictement supérieure à 5
print("Éléments pairs :\n", matrix[matrix % 2 == 0], "\n")  # extrait tous les éléments qui sont des nombres pairs (reste = 0 quand divisé par 2)

### 🧩 Exercice

> À partir d’un tableau `array = np.arange(35).reshape(5, 7)`, répondez aux questions suivantes :  
> 1. Affichez l’élément situé à la 3e ligne et 5e colonne.  
> 2. Affichez toute la 2e ligne du tableau. 
> 3. Affichez toute la dernière colonne. 
> 4. Affichez les trois premières lignes du tableau. 
> 5. Affichez les colonnes 2 à 5 de toutes les lignes. 
> 6. Affichez les 3 derniers éléments de la 4e ligne.
> 7. Affichez une ligne sur deux (lignes 0, 2, 4).  
> 8. Affichez une colonne sur trois (colonnes 0, 3, 6).
> 9. Affichez tous les éléments strictement supérieurs à 25.
> 10. Affichez tous les éléments impairs du tableau.
> 11. Affichez tous les éléments compris entre 10 et 20 inclus.
> 12. Remplacez l’élément en ligne 1, colonne 4 par 999.
> 13. Remplacez tous les éléments multiples de 7 par -7.
> 14. Remplacez la 3e colonne par des zéros.

In [67]:
# Votre code ici
array = np.arange(35).reshape(5, 7)
#1. Affichez l’élément situé à la 3e ligne et 5e colonne.  
array[3,5]
#2. Affichez toute la 2e ligne du tableau. 
array[2]
#3. Affichez toute la dernière colonne. 
array[:,-1]
# 4. Affichez les trois premières lignes du tableau. 
array[:3]
#5. Affichez les colonnes 2 à 5 de toutes les lignes. 
array[:,2:5]
#6. Affichez les 3 derniers éléments de la 4e ligne.
print(f"les 3 derniers éléments de la 4e ligne{array[4,-3:]}")

print(f" une ligne sur deux (lignes 0, 2, 4) : { array[::2]}")  
print(f"Affichez une colonne sur trois (colonnes 0, 3, 6). {array[:,::3]}")
print(f"Affichez tous les éléments strictement supérieurs à 25. {array[array > 25]}")
print(f"Affichez tous les éléments impairs du tableau. { array[array % 2 != 0]}")
print(f"Affichez tous les éléments compris entre 10 et 20 inclus. { array[(array > 10) &  (array <= 20)]}")
array[1][4] = 999
print(f"Remplacez l'élément en ligne 1, colonne 4 par 999. {array[1][4]}")
for i in range(array.shape[0]):
    for j in range(array.shape[1]):
        if array[i][j] % 7 == 0:
            array[i][j] = -7
        
print(f"Remplacez tous les éléments multiples de 7 par -7. {array}")
array[:,3] = np.zeros(array.shape[0])
print(f"Remplacez la 3e colonne par des zéros. {array}")

les 3 derniers éléments de la 4e ligne[32 33 34]
 une ligne sur deux (lignes 0, 2, 4) : [[ 0  1  2  3  4  5  6]
 [14 15 16 17 18 19 20]
 [28 29 30 31 32 33 34]]
Affichez une colonne sur trois (colonnes 0, 3, 6). [[ 0  3  6]
 [ 7 10 13]
 [14 17 20]
 [21 24 27]
 [28 31 34]]
Affichez tous les éléments strictement supérieurs à 25. [26 27 28 29 30 31 32 33 34]
Affichez tous les éléments impairs du tableau. [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33]
Affichez tous les éléments compris entre 10 et 20 inclus. [11 12 13 14 15 16 17 18 19 20]
Remplacez l'élément en ligne 1, colonne 4 par 999. 999
Remplacez tous les éléments multiples de 7 par -7. [[ -7   1   2   3   4   5   6]
 [ -7   8   9  10 999  12  13]
 [ -7  15  16  17  18  19  20]
 [ -7  22  23  24  25  26  27]
 [ -7  29  30  31  32  33  34]]
Remplacez la 3e colonne par des zéros. [[ -7   1   2   0   4   5   6]
 [ -7   8   9   0 999  12  13]
 [ -7  15  16   0  18  19  20]
 [ -7  22  23   0  25  26  27]
 [ -7  29  30   0  32  33  

# 4. ➕ Opérations vectorielles

Lorsqu’on travaille avec des tableaux NumPy (vecteurs ou matrices), on peut effectuer des opérations mathématiques directement sur l’ensemble des éléments, sans utiliser de boucles. On parle d’**opérations vectorielles** ou **opérations élément par élément**.

Cela permet :
- d’écrire du code plus simple et plus lisible,
- d’obtenir des calculs bien plus rapides grâce à l’optimisation interne de NumPy,
- de manipuler facilement des données numériques comme dans les domaines de la data science ou du machine learning.

**🤖 Pourquoi les opérations vectorielles sont essentielles en machine learning ?**

Dans le machine learning, on travaille en permanence avec :
- des vecteurs : chaque ligne de données (ex : un utilisateur avec ses caractéristiques) est un vecteur,
- des matrices : un ensemble de données (ex : tous les utilisateurs) forme une matrice,
- et des opérations mathématiques rapides pour entraîner et utiliser les modèles.


In [ ]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])

# Addition élément par élément
print("Addition :", x + y)  # [11 22 33]

# Soustraction élément par élément
print("Soustraction :", x - y)  # [-9 -18 -27]

# Multiplication élément par élément (produit Hadamard)
print("Multiplication :", x * y)  # [10 40 90]

# Division élément par élément
print("Division :", y / x)  # [10. 10. 10.]

# Exponentiation
print("Carrés de x :", x ** 2)  # [1 4 9]

# Produit scalaire (dot product)
print("Produit scalaire (x @ y) :", x @ y)  # 140
print("Produit scalaire (np.dot) :", np.dot(x, y))  # 140

# Norme (longueur du vecteur)
print("Norme de x :", np.linalg.norm(x))  # sqrt(1^2 + 2^2 + 3^2) = 3.7416...

### 🧩 Exercices

> Soit `x = np.array([2, 4, 6])` et `y = np.array([1, 3, 5])`  
> 1. Calculez x + y  
> 2. Calculez x - y  
> 3. Calculez x * y (multiplication élément par élément)  
> 4. Calculez x / y (division élément par élément)

In [69]:
# Votre code ici

x = np.array([2, 4, 6])
y = np.array([1, 3, 5])

print(f" x + y : { x + y }")
print(f" x - y : { x - y }")
print(f" x * y : { x * y }")
print(f" x / y : { x / y }")

 x + y : [ 3  7 11]
 x - y : [1 1 1]
 x * y : [ 2 12 30]
 x / y : [2.         1.33333333 1.2       ]


> Reprenez les vecteurs x et y ci-dessus  
> 1. Calculez le carré de chaque élément de x  
> 2. Calculez le double de chaque élément de y  
> 3. Ajoutez 10 à tous les éléments de x

In [70]:
# Votre code ici
print(f" le carré de chaque élément de x : {x **2}")
print(f"le double de chaque élément de y : {x *2}")
print(f" Ajoutez 10 à tous les éléments de x : {x + (np.ones(x.shape)*10)}")


 le carré de chaque élément de x : [ 4 16 36]
le double de chaque élément de y : [ 4  8 12]
 Ajoutez 10 à tous les éléments de x : [12. 14. 16.]


> Soit `x = np.array([1, 2, 3])` et `y = np.array([4, 5, 6])`  
> 1. Calculez le **produit scalaire** de x et y avec `@`  
> 2. Calculez le produit scalaire avec `np.dot()`  
> 3. Vérifiez que les deux résultats sont identiques

In [72]:
# Votre code ici
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(f"le **produit scalaire** de x et y avec `@` {x @ y}")
print(f"le **produit scalaire** de x et y avec `np.dot` {np.dot(x,y)}")


le **produit scalaire** de x et y avec `@` 32
le **produit scalaire** de x et y avec `np.dot` 32


> Soit `v = np.array([3, 4])`  
> 1. Calculez la **norme** de v (indice : `np.linalg.norm`)  
> 2. Normalisez v (divisez chaque élément par la norme)  
> 3. Vérifiez que la norme du vecteur normalisé vaut 1

In [82]:
# Votre code ici
v = np.array([3, 4])
norm_v = np.linalg.norm(v)
print(f" la **norme** de v: {np.linalg.norm(v)}")
v_div = v/norm_v
np.linalg.norm(v_div)





 la **norme** de v: 5.0


np.float64(1.0)

> Créez deux vecteurs a et b de taille 5, remplis avec des entiers de votre choix  
> 1. Faites la somme, la différence et le produit terme à terme  
> 2. Calculez la somme totale des éléments de a et de b  
> 3. Calculez la moyenne des éléments de a

In [88]:
# Votre code ici
a = np.arange(5)

b = np.array(np.random.rand(5))

print(a+b)
print(np.mean(a))

[0.46491242 1.19987184 2.80793359 3.19276066 4.93338651]
2.0


# 5. 📊 Fonctions statistiques utiles

NumPy propose de nombreuses fonctions pour analyser rapidement des données numériques : **maximum**, **minimum**, **moyenne**, **écart-type**, **somme**, etc. Ces fonctions permettent d’obtenir des indicateurs statistiques simples sur un tableau, qu’il soit 1D (vecteur) ou 2D (matrice).

## 5.1. Vecteur 1D

In [ ]:
# Tableau de 10 entiers aléatoires entre 0 et 99
arr = np.random.randint(0, 100, (10,))

print("Tableau :", arr)
print("Max :", arr.max())                # Valeur maximale du tableau
print("Min :", arr.min())                # Valeur minimale du tableau
print("Moyenne :", arr.mean())           # Moyenne arithmétique
print("Écart-type :", arr.std())         # Écart-type (dispersion des valeurs)
print("Somme :", arr.sum())              # Somme de tous les éléments
print("Indice du max :", arr.argmax())   # Position (indice) de la valeur maximale
print("Indice du min :", arr.argmin())   # Position (indice) de la valeur minimale

## 5.2. Matrice 2D

In [89]:
# matrice 4x5 d'entiers aléatoires entre 0 et 99
matrix = np.random.randint(0, 100, (4, 5))

print("Matrice :\n", matrix, "\n")

print("Moyenne globale :", matrix.mean(), "\n")              # Moyenne de tous les éléments
print("Moyenne par ligne :", matrix.mean(axis=1), "\n")      # Moyenne de chaque ligne
print("Moyenne par colonne :", matrix.mean(axis=0), "\n")    # Moyenne de chaque colonne
print("Somme par colonne :", matrix.sum(axis=0), "\n")       # Somme de chaque colonne

Matrice :
 [[38 60 37 55 36]
 [ 9 42 98 69 70]
 [18 93 93 79 64]
 [ 3 50 27  1 69]] 

Moyenne globale : 50.55 

Moyenne par ligne : [45.2 57.6 69.4 30. ] 

Moyenne par colonne : [17.   61.25 63.75 51.   59.75] 

Somme par colonne : [ 68 245 255 204 239] 



### 🧩 Exercices

> Générez un tableau de 15 entiers aléatoires entre 1 et 100.  
> Affichez la valeur maximale, la valeur minimale et leur écart.

In [93]:
# Votre code ici
print("max", np.random.randint(1,100,15).max())
print("min", np.random.randint(1,100,15).min())


max 90
min 1


> Générez un tableau de 20 entiers aléatoires entre 0 et 50.  
> Affichez la somme, la moyenne et la variance.

In [94]:
# Votre code ici
print("sum", np.random.randint(1,50,20).sum())
print("mean", np.random.randint(1,50,20).mean())
print("variance", np.random.randint(1,50,20).var())

sum 450
mean 23.4
variance 173.2875


> Créez une matrice 5x4 d’entiers aléatoires entre 0 et 99.  
> Affichez la moyenne de chaque ligne et la moyenne de chaque colonne.

In [99]:
# Votre code ici
M_5x4 = np.random.randint(0,99,(5,4))
M_5x4
print("moy chaque ligne", M_5x4.mean(axis=1))
print("moy chaque colonne", M_5x4.mean(axis=0))

moy chaque ligne [20.   45.25 47.25 47.5  58.  ]
moy chaque colonne [28.  39.4 66.  41. ]


> Générez une matrice 6x3 d'entiers aléatoires.  
> Affichez l’indice du maximum global, puis l’indice du maximum de chaque ligne.

In [111]:
# Votre code ici
M_6x3 = (np.random.random((6, 3)) * 100).astype(int)
M_6x3
print(" indice du max", M_6x3.argmax())
for i in range(M_6x3.shape[0]):
    print(f" indice du max de ligne {i} :", M_6x3[i,:].argmax())


 indice du max 11
 indice du max de ligne 0 : 2
 indice du max de ligne 1 : 0
 indice du max de ligne 2 : 2
 indice du max de ligne 3 : 2
 indice du max de ligne 4 : 0
 indice du max de ligne 5 : 0


> Créez un tableau de 12 flottants aléatoires entre 0 et 1.  
> Comptez combien de valeurs sont supérieures à la moyenne.

In [115]:
# Votre code ici
M12 = np.random.rand(12)
print(M12)
print(f"num value > mean : {len(M12[M12>M12.mean()])}")

[0.95585358 0.77713617 0.56121001 0.22202431 0.38070545 0.39742094
 0.86681526 0.15577071 0.76941479 0.09086967 0.88766127 0.70721433]
num value > mean : 6


> Générez un tableau de 50 entiers entre 10 et 100.  
> Calculez le 25e, le 50e (médiane) et le 75e percentile.

In [117]:
# Votre code ici

M50 = np.random.randint(10,100,50)

print("le 25e, le 50e (médiane) et le 75e percentile:",np.quantile(M50,[0.25,0.50,0.75]))

le 25e, le 50e (médiane) et le 75e percentile: [29.5  58.5  77.75]


# 6. 🔧 Empilement et fusion de tableaux

Il est souvent nécessaire de combiner plusieurs tableaux NumPy pour former des structures plus grandes.  
Cela peut se faire en ajoutant des lignes (empilement vertical) ou des colonnes (empilement horizontal).

NumPy propose plusieurs fonctions pour cela :

- `np.vstack` : empilement dans le sens **vertical** (ajoute des lignes)
- `np.hstack` : empilement dans le sens **horizontal** (ajoute des colonnes)
- `np.concatenate` : fusion plus générale, où l’on choisit l’axe (`axis=0` pour les lignes, `axis=1` pour les colonnes)

⚠️ Pour que ces opérations fonctionnent, les **dimensions doivent être compatibles** :
- Pour empiler verticalement, les **nombres de colonnes doivent être identiques**
- Pour empiler horizontalement, les **nombres de lignes doivent être identiques**

In [ ]:
a = np.array([[1, 2], [3, 4]])  # matrice 2x2
b = np.array([[5, 6]])          # matrice 1x2


# Empilement vertical : ajoute des lignes (mêmes nombres de colonnes requis)
vstacked = np.vstack([a, b])
print("Empilement vertical (vstack) :\n", vstacked, "\n")

# Empilement horizontal : ajoute des colonnes (mêmes nombres de lignes requis)
hstacked = np.hstack([a, a])
print("Empilement horizontal (hstack) :\n", hstacked, "\n")


# Fusion avec np.concatenate (plus général)
conc_v = np.concatenate([a, b], axis=0)  # même que vstack
print("Concaténation verticale :\n", conc_v, "\n")

conc_h = np.concatenate([a, a], axis=1)  # même que hstack
print("Concaténation horizontale :\n", conc_h, "\n")


# 💡 INFO :
# np.vstack([a, b]) et np.concatenate([a, b], axis=0) donnent exactement le même résultat :
# → ils empilent les tableaux verticalement (ajout de lignes).

# De même, np.hstack([a, a]) et np.concatenate([a, a], axis=1) sont aussi équivalents :
# → ils empilent les tableaux horizontalement (ajout de colonnes).

# ✅ vstack / hstack sont plus lisibles pour débuter,
# ✅ concatenate est plus flexible (surtout utile pour des tableaux à plus de 2 dimensions).

### 🧩 Exercices

> Créez deux matrices compatibles pour un empilement vertical :  
> - une matrice `a` de forme `(2, 3)`  
> - une matrice `b` de forme `(1, 3)`  
> - Utilisez `np.vstack()` pour les empiler.

In [121]:
# Votre code ici
a = np.random.rand(2,3)
a
b = np.random.rand(1,3)
b
c = np.vstack([a,b])
c

array([[0.59543742, 0.11151581, 0.47743343],
       [0.77578544, 0.68452458, 0.7420063 ],
       [0.52797188, 0.19222312, 0.66376906]])

> Reprenez les mêmes matrices que précdemment et utilisez np.concatenate() avec axis=0 pour vérifier qu’on obtient le même résultat qu’avec vstack.

In [122]:
# Votre code ici
c = np.concatenate([a,b], axis = 0 )
c

array([[0.59543742, 0.11151581, 0.47743343],
       [0.77578544, 0.68452458, 0.7420063 ],
       [0.52797188, 0.19222312, 0.66376906]])

> Reprenez les mêmes matrices que précédemment et utilisez np.concatenate() avec axis=1 pour vérifier qu’on obtient le même résultat qu’avec hstack.

In [127]:
# Votre code ici

d = np.concatenate([a,a], axis = 1 )
d
d = np.hstack([a,a])
d

array([[0.59543742, 0.11151581, 0.47743343, 0.59543742, 0.11151581,
        0.47743343],
       [0.77578544, 0.68452458, 0.7420063 , 0.77578544, 0.68452458,
        0.7420063 ]])

# 7. 📡 Broadcasting (adaptation automatique des dimensions)

En NumPy, les opérations entre tableaux (addition, soustraction, etc.) nécessitent normalement que les formes (shape) soient **compatibles**.

Mais au lieu de lever une erreur quand les formes sont différentes, NumPy applique parfois automatiquement une règle intelligente d’adaptation des dimensions : c’est ce qu’on appelle le **broadcasting** (ou diffusion en français).

In [74]:
A = np.array([[1], [2], [3]])  # Matrice de forme (3, 1) : vecteur colonne
B = np.array([10, 20, 30])     # Vecteur ligne de forme (3,)

print("A.shape =", A.shape, "\n")    # Affiche la forme de A : (3, 1)
print("B.shape =", B.shape, "\n")    # Affiche la forme de B : (3,)

# NumPy étend automatiquement A horizontalement (comme si on le copiait 3 fois en colonnes) pour l’aligner avec B (qui est traité comme une ligne).
# Résultat : addition élément par élément dans une matrice de forme (3, 3)
print("Résultat du broadcasting :\n", A + B)

A.shape = (3, 1) 

B.shape = (3,) 

Résultat du broadcasting :
 [[11 21 31]
 [12 22 32]
 [13 23 33]]


### 🧩 Exercices

> Créez un vecteur `a = np.array([1, 2, 3])`.  
> Ajoutez le scalaire `5` à ce vecteur. Que se passe-t-il ?

In [75]:
# Votre code ici
a = np.array([1, 2, 3])
print(a+5)

[6 7 8]


> Créez une matrice `M` de forme (3, 4) avec `np.ones((3, 4))`.  
> Créez un vecteur `v = np.array([10, 20, 30, 40])`.  
> Faites `M + v` et observez le résultat.

In [76]:
# Votre code ici
M = np.ones((3, 4))
v = np.array([10, 20, 30, 40])
print(M+v)


[[11. 21. 31. 41.]
 [11. 21. 31. 41.]
 [11. 21. 31. 41.]]


> Créez une matrice `M = np.ones((3, 4))`.  
> Créez un vecteur colonne `v = np.array([[1], [2], [3]])`.  
> Faites `M + v`. Pourquoi cela fonctionne ?

In [77]:
# Votre code ici
M = np.ones((3, 4))
v = np.array([[1], [2], [3]])
print(M+v)

[[2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]]


> Créez `A = np.array([[1], [2], [3]])` (forme 3x1)  
> Créez `B = np.array([10, 20])` (forme 2,)  
> Essayez `A + B`. Que se passe-t-il ? Pourquoi ?

In [78]:
# Votre code ici
A = np.array([[1], [2], [3]])
B = np.array([10, 20])
print(A+B)

[[11 21]
 [12 22]
 [13 23]]


> Créez `X = np.ones((2, 3, 4))`  
> Créez `Y = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120]])` (forme 3x4)  
> Essayez `X + Y` et observez la forme du résultat.

In [80]:
# Votre code ici
X = np.ones((2, 3, 4))
print(X)

Y = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120]])
print(X+Y)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[[ 11.  21.  31.  41.]
  [ 51.  61.  71.  81.]
  [ 91. 101. 111. 121.]]

 [[ 11.  21.  31.  41.]
  [ 51.  61.  71.  81.]
  [ 91. 101. 111. 121.]]]


---
## ✅ Bravo !
Vous connaissez maintenant les bases essentielles de NumPy. Vous allez pouvoir aborder d'autres libriaries telles que **Pandas** ou **Scikit-learn**.